import {worlds,type World} from './journey';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {ArrowUpRight,AudioLines,ChevronDown,Expand,ImagePlus,Info,Maximize2,Mic,Monitor,Music2,Pause,Play,RefreshCw,Shuffle,SlidersHorizontal,X,Camera,Check,Orbit,ArrowLeft} from 'lucide-react';
import {useControls,type Quality,type Palette,type Aspect} from './store';
import {AudioManager,type AudioStatus} from './audio';
import {Organism,type RenderStats} from './organism';
import {emptyFeatures} from './signals';

const initialAudio:AudioStatus={state:'idle',label:'No audio connected',message:'Add sound. Give it a pulse.',kind:'none'};
const download=(blob:Blob,name:string)=>{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function Slider({label,control}:{label:string;control:'energy'|'motion'|'detail'|'glow'|'reactivity'|'imageMix'}){const value=useControls(s=>s[control]);const set=useControls(s=>s.set);return <label className="slider"><span>{label}<output>{Math.round(value*100)}<small>%</small></output></span><input aria-label={label} type="range" min="0" max="1" step="0.01" value={value} style={{'--fill':`${value*100}%`} as CSSProperties} onChange={e=>set(control,+e.target.value)}/></label>;}
export function App(){
 const host=useRef<HTMLDivElement>(null),engine=useRef<Organism|null>(null),audio=useRef<AudioManager|null>(null),imageGeneration=useRef(0);
 const [source,setSource]=useState(initialAudio),[stats,setStats]=useState<RenderStats|null>(null),[features,setFeatures]=useState(emptyFeatures()),[error,setError]=useState(''),[toast,setToast]=useState('');
 const [panel,setPanel]=useState<'audio'|'image'|'info'|null>(null),[controlsOpen,setControlsOpen]=useState(window.innerWidth>600),[zen,setZen]=useState(false),[imageName,setImageName]=useState(''),[imagePreview,setImagePreview]=useState(''),[imageLoading,setImageLoading]=useState(false),[advanced,setAdvanced]=useState(false);
 const s=useControls();const audioInput=useRef<HTMLInputElement>(null),imageInput=useRef<HTMLInputElement>(null);const toastTimer=useRef(0);
 const notify=(text:string)=>{setToast(text);clearTimeout(toastTimer.current);toastTimer.current=window.setTimeout(()=>setToast(''),3500);};
 useEffect(()=>{const manager=new AudioManager();audio.current=manager;manager.onChange=setSource;try{const e=new Organism(host.current!,manager);engine.current=e;e.onStats=setStats;e.onFeatures=f=>setFeatures({...f});e.onError=setError;}catch(e){setError(e instanceof Error?e.message:'WebGL2 could not start. Enable hardware acceleration and reload.');}return()=>{engine.current?.dispose();manager.dispose();clearTimeout(toastTimer.current);};},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches('input,select,textarea,button'))return;if(e.key==='Escape'){setZen(false);setPanel(null);}if(e.key.toLowerCase()==='h')setZen(v=>!v);if(e.code==='Space'){e.preventDefault();useControls.getState().set('playing',!useControls.getState().playing);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 useEffect(()=>()=>{if(imagePreview)URL.revokeObjectURL(imagePreview);},[imagePreview]);
 async function imageFile(file?:File){if(!file)return;const id=++imageGeneration.current;setImageLoading(true);try{if(!file.type.startsWith('image/'))throw Error('Choose a PNG, JPEG, WebP, or another supported image.');await engine.current?.setImage(file);if(id!==imageGeneration.current)return;setImageName(file.name);setImagePreview(URL.createObjectURL(file));notify('Image woven into the organism');}catch(e){notify(e instanceof Error?e.message:'Image could not be loaded.');}finally{if(id===imageGeneration.current)setImageLoading(false);}}
 const fullscreen=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{notify('Fullscreen unavailable. Try focus mode instead.');}};
 const capture=async()=>{try{if(!engine.current)return;download(await engine.current.capture(),`lucidXO-${s.seed}-${stats?.width}x${stats?.height}.png`);notify('Frame captured');}catch{notify('Could not capture this frame.');}};
 const ratio=s.aspect==='Fit'?undefined:s.aspect.replace(':','/');
 return <main className={`app ${zen?'zen':''}`}>
  <div className="stage-shell"><div className={`stage ${ratio?'framed':''}`} style={ratio?{aspectRatio:ratio,'--aspect':s.aspect.split(':').map(Number).reduce((a,b)=>a/b)} as CSSProperties:undefined} ref={host}/></div><div className="grain"/><div className="vignette"/>
  {!zen&&<>
  <header><a href="https://github.com/shubhamshukla300498-WED/LucidXO" target="_blank" rel="noreferrer" className="brand" aria-label="lucidXO project on GitHub">lucid<span>XO</span><i/></a><div className="header-caption">A LIVING AUDIOVISUAL INSTRUMENT</div><div className="header-actions"><span className="version">EXPERIMENT 001</span><button className="icon-button" title="About lucidXO" aria-label="About lucidXO" onClick={()=>setPanel(panel==='info'?null:'info')}><Info size={17}/></button><button className="focus-button" onClick={()=>setZen(true)}><Expand size={14}/> Enter focus</button></div></header>
  <section className="world-title"><div className="eyebrow"><span className="status-dot"/> LIVE GENERATIVE WORLD <span className="slash">/</span> 01</div><h1>{s.world.split(' ')[0]}<br/><em>{s.world.split(' ').slice(1).join(' ')}.</em></h1><p>Somewhere between a life form<br/>and a frequency.</p><div className="world-tags"><span>RECURSIVE ANATOMY</span><span>IRIDESCENT MATTER</span></div></section>
  <aside className={`controls ${controlsOpen?'':'closed'}`}><button className="controls-heading" aria-expanded={controlsOpen} onClick={()=>setControlsOpen(!controlsOpen)}><span><SlidersHorizontal size={15}/> Shape the organism</span><ChevronDown size={15}/></button>
   {controlsOpen&&<div className="controls-body"><div className="control-section quality-section"><label>World<select aria-label="Visual world" value={s.world} onChange={e=>{s.set('journey',false);s.set('world',e.target.value as World);}}>{worlds.map(w=><option key={w}>{w}</option>)}</select></label><label>Journey<input type="checkbox" aria-label="Automatic journey" checked={s.journey} onChange={e=>s.set('journey',e.target.checked)}/></label><p className="quality-note">{s.journey?'6–10s holds · 2s morphs':'Holding this world · choose another to morph'}</p></div><div className="control-section"><div className="section-label">LIVING SYSTEM</div><Slider label="Energy" control="energy"/><Slider label="Motion" control="motion"/><Slider label="Detail" control="detail"/><Slider label="Glow" control="glow"/></div>
    <div className="control-section"><div className="section-label">MATERIAL PALETTE</div><div className="palettes">{(['Iridescent','Ember','Verdant'] as Palette[]).map(p=><button key={p} title={p} aria-label={`${p} palette`} aria-pressed={s.palette===p} onClick={()=>s.set('palette',p)} className={`palette ${p.toLowerCase()} ${s.palette===p?'selected':''}`}><span/>{s.palette===p&&<Check size={12}/>}</button>)}<span className="palette-label">{s.palette}</span></div></div>
    <div className="control-section quality-section"><label>Render quality<select aria-label="Render quality" value={s.quality} onChange={e=>{s.set('quality',e.target.value as Quality);if(e.target.value==='Native 4K'&&s.aspect==='Fit')s.set('aspect','16:9');}}>{(['Performance','Balanced','Native 4K'] as Quality[]).map(v=><option key={v}>{v}</option>)}</select></label><label>Frame<select aria-label="Aspect ratio" value={s.aspect} onChange={e=>s.set('aspect',e.target.value as Aspect)}>{['Fit','16:9','9:16','1:1','4:5'].map(v=><option key={v}>{v}</option>)}</select></label><p className="quality-note">{s.quality==='Native 4K'?'Native scene resolution · GPU intensive':'Scene capped at '+(s.quality==='Balanced'?'1920':'1280')+'px · lighter on your GPU'}</p></div>
    <button className="generate-button" onClick={()=>{s.set('seed',Math.floor(Math.random()*90000)+10000);notify('A new organism is growing');}}><Shuffle size={15}/> Generate variation <span>↗</span></button><div className="seed-line">SEED {String(s.seed).padStart(5,'0')}<button title="Reset controls and camera" aria-label="Reset controls" onClick={()=>{s.reset();engine.current?.resetCamera();notify('Restored original organism');}}><RefreshCw size={12}/></button></div>
   </div>}
  </aside>
  <div className="canvas-label"><span className="crosshair">+</span><span>DRAG TO EXPLORE<br/><small>SCROLL TO MOVE CLOSER</small></span></div>
  <section className="bottom-dock"><div className="sound-status"><div className={`wave-icon ${source.state==='active'?'active':''}`}>{[.4,.85,.55,1,.6,.8,.35].map((n,i)=><i key={i} style={{height:`${8+n*(source.state==='active'?features.energy*35+8:12)}px`}}/>)}</div><div><span className="dock-caption">{source.state==='active'?'AUDIO CONNECTED':'LET SOUND TAKE OVER'}</span><button className="source-name" onClick={()=>setPanel(panel==='audio'?null:'audio')}>{source.label}<ChevronDown size={12}/></button></div></div><div className="dock-divider"/><button className={`dock-button ${panel==='audio'?'active':''}`} onClick={()=>setPanel(panel==='audio'?null:'audio')} aria-label="Connect audio"><AudioLines size={17}/><span>Connect audio</span></button><button className={`dock-button ${imageName?'active':''}`} aria-label="Add an image" onClick={()=>setPanel(panel==='image'?null:'image')}><ImagePlus size={17}/><span>{imageName?'Image connected':'Add an image'}</span></button><div className="dock-spacer"/><button className="icon-button" title={s.playing?'Pause motion':'Resume motion'} aria-label={s.playing?'Pause motion':'Resume motion'} onClick={()=>s.set('playing',!s.playing)}>{s.playing?<Pause size={16}/>:<Play size={16}/>}</button><button className={`icon-button ${s.orbit?'enabled':''}`} aria-label="Toggle automatic orbit" aria-pressed={s.orbit} title="Automatic orbit" onClick={()=>s.set('orbit',!s.orbit)}><Orbit size={17}/></button><button className="icon-button" aria-label="Save frame" title="Save frame as PNG" onClick={capture}><Camera size={17}/></button><button className="icon-button" aria-label="Fullscreen" title="Fullscreen" onClick={fullscreen}><Maximize2 size={16}/></button></section>
  <footer><span>PROCEDURAL. UNREPEATABLE. ALIVE.</span><button onClick={()=>setAdvanced(!advanced)} aria-label="Render details" className="render-status"><span className="status-dot"/>{stats?`${stats.fps} FPS`:'INITIALIZING'}<i/>{stats?`${stats.width} × ${stats.height}`:'WEBGL2'}<i/>{s.quality.toUpperCase()}</button></footer>
  </>}
  {zen&&<button className="exit-focus" onClick={()=>setZen(false)}><ArrowLeft size={14}/> Exit focus <kbd>H</kbd></button>}
  {panel&&!zen&&<div className={`panel ${panel==='info'?'about-panel':''}`} role="dialog" aria-label={panel==='audio'?'Connect audio':panel==='image'?'Image influence':'About lucidXO'}><button className="panel-close icon-button" aria-label="Close panel" onClick={()=>setPanel(null)}><X size={17}/></button>
   {panel==='audio'&&<><div className="eyebrow">GIVE IT A PULSE</div><h2>Choose your sound.</h2><p>The organism listens. Every frequency finds its own form.</p><div className="source-options"><button onClick={()=>audioInput.current?.click()}><Music2/><span>Audio file<small>MP3, WAV, OGG and more</small></span><ArrowUpRight size={16}/></button><button onClick={()=>void audio.current?.capture('mic')}><Mic/><span>Microphone<small>Listen to the room around you</small></span><ArrowUpRight size={16}/></button><button onClick={()=>void audio.current?.capture('tab')}><Monitor/><span>Browser tab<small>Select a tab and enable Share audio</small></span><ArrowUpRight size={16}/></button></div><button className="demo-button" onClick={()=>void audio.current?.demo()}><Play size={14}/> Try the built-in sound <span>100 BPM</span></button><div className="audio-message" role="status"><span className={`status-dot ${source.state==='error'?'error':''}`}/>{source.message}</div>{source.kind!=='none'&&<div className="playback"><span>{source.label}</span>{source.kind==='file'&&<button aria-label="Toggle audio playback" onClick={()=>audio.current?.toggle()}>{source.state==='paused'?<Play size={14}/>:<Pause size={14}/>}</button>}<button onClick={()=>audio.current?.stop()}>Disconnect</button></div>}<Slider label="Audio reactivity" control="reactivity"/><p className="privacy">Your audio stays in your browser.</p></>}
   {panel==='image'&&<><div className="eyebrow">A TRACE OF YOUR WORLD</div><h2>Weave in an image.</h2><p>Your image becomes color and surface detail across the living anatomy.</p><button className="image-drop" onClick={()=>imageInput.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void imageFile(e.dataTransfer.files[0]);}}>{imagePreview?<img src={imagePreview} alt="Current image influencing the organism"/>:<><ImagePlus size={30}/><span>Drop an image, or browse</span><small>PNG · JPEG · WebP</small></>}</button>{imageName&&<div className="playback"><span>{imageName}</span><button onClick={()=>{imageGeneration.current++;engine.current?.clearImage();setImageName('');setImagePreview('');setImageLoading(false);}}>Remove</button></div>}{imageLoading&&<p role="status">Preparing your image…</p>}<Slider label="Image influence" control="imageMix"/><p className="privacy">Images are processed locally, at up to 2048px.</p></>}
   {panel==='info'&&<><div className="eyebrow">EXPERIMENT 001</div><h2>A living frequency.</h2><p>lucidXO explores the space between generative art, imagined biology, and sound.</p><p>Explore eight worlds, including spiral webs, solar petals, silk sheets, mirrored corridors, and alien masks. Bass slowly shapes the tunnel, kick attacks send gold rings into depth, midrange hits send magenta waves, and highs light cyan details. Automatic camera movement follows the music smoothly. Journey advances after musical onsets, with a timed fallback while sound is active.</p><div className="about-grid"><span>DRAG<small>Look around</small></span><span>SCROLL<small>Move closer</small></span><span>SPACE<small>Pause motion</small></span><span>H<small>Focus mode</small></span></div><p>Native 4K is an explicit rendering mode, not a promise of 60 FPS on every device. Actual dimensions and measured frame rate appear below.</p><a className="project-link" href="https://github.com/shubhamshukla300498-WED/LucidXO" target="_blank" rel="noreferrer">Explore the project <ArrowUpRight size={15}/></a></>}
  </div>}
  {advanced&&stats&&!zen&&<div className="stats-panel"><button className="panel-close icon-button" aria-label="Close render details" onClick={()=>setAdvanced(false)}><X size={14}/></button><div className="section-label">RENDER DETAILS</div><p>{stats.gpu}</p><dl><dt>Frame interval</dt><dd>{stats.frameMs.toFixed(1)} ms</dd><dt>P95 since quality change</dt><dd>{stats.p95.toFixed(1)} ms</dd><dt>Primary scene</dt><dd>{stats.width} × {stats.height}</dd><dt>Triangles / frame</dt><dd>{stats.triangles.toLocaleString()}</dd><dt>Draw calls</dt><dd>{stats.calls}</dd><dt>Geometries / textures</dt><dd>{stats.geometries} / {stats.textures}</dd><dt>Bass / mid / high</dt><dd>{features.bass.toFixed(2)} / {features.mid.toFixed(2)} / {features.high.toFixed(2)}</dd><dt>Kick / mid hit / high hit</dt><dd>{features.kick.toFixed(2)} / {features.snare.toFixed(2)} / {features.hat.toFixed(2)}</dd><dt>Onset pulse</dt><dd>{features.onset.toFixed(2)}</dd><dt>GPU pass timing</dt><dd>Not measured</dd></dl><button className="text-button" onClick={()=>download(new Blob([JSON.stringify({timestamp:new Date().toISOString(),userAgent:navigator.userAgent,controls:s,stats,audio:source.kind},null,2)],{type:'application/json'}),'lucidXO-render-report.json')}>Export render report ↗</button></div>}
  {error&&<div className="error-banner" role="alert">{error}<button onClick={()=>location.reload()}>Reload renderer</button></div>}{toast&&<div className="toast" role="status"><Check size={14}/>{toast}</div>}
  <input ref={audioInput} aria-label="Upload audio file" type="file" accept="audio/*" hidden onChange={e=>{const file=e.target.files?.[0];if(file)void audio.current?.load(file);e.target.value='';}}/>
  <input ref={imageInput} aria-label="Upload image file" type="file" accept="image/*" hidden onChange={e=>{void imageFile(e.target.files?.[0]);e.target.value='';}}/>
 </main>;
}
